require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/arclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'arclight.gemspec'
    - 'spec/**/*'
    - 'tasks/**/*'

Performance/RegexpMatch:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/arclight.rb'

Bundler/DuplicatedGem:
  Enabled: false
