require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/arclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'spec/features/traject/ead2_indexing_spec.rb'


Rails:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false
