require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/arclight/templates/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'spec/features/traject/ead2_indexing_spec.rb'
    - 'spec/helpers/arclight_helper_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/arclight_helper.rb'

Rails:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false
