require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/arclight/templates/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Rails:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /\.rake$/
    - 'arclight.gemspec'
    - 'spec/**/*'
    - 'lib/arclight/custom_document.rb'
    - 'lib/generators/arclight/templates/catalog_controller.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/generators/arclight/templates/catalog_controller.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'lib/arclight/custom_document.rb'  # XPaths get long
    - 'lib/arclight/custom_component.rb' # XPaths get long
    - 'lib/generators/arclight/templates/catalog_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/arclight/custom_document.rb' # arclight_field_definitions too long

Metrics/ModuleLength:
  Max: 120

Performance/RegexpMatch:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'app/controllers/concerns/arclight/field_config_helpers.rb' # html_safe needs to be called to mimic BL JOIN behavior

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/lib/arclight/viewers/oembed_spec.rb' # Default file path is o_embed, and that looks weird

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/arclight.rb'
    - 'lib/generators/arclight/templates/catalog_controller.rb'


