sudo: false
language: ruby
notifications:
  email: false
rvm:
  - 2.4.1
jdk:
  - oraclejdk8
cache: bundler
before_script:
  - xmllint --noout --schema spec/fixtures/xsd/ead.xsd spec/fixtures/ead/*.xml
addons:
  apt:
    sources:
      - libxml2-utils