sudo: false
language: ruby
notifications:
  email: false
rvm:
  - 2.5.1
jdk:
  - oraclejdk8

before_script:
  - find spec/fixtures/ead -name '*.xml' | xargs xmllint --noout --schema spec/fixtures/xsd/ead.xsd
addons:
  apt:
    packages:
    - libxml2-utils
  chrome: stable
